### ISSUE TITLE
Docker pSTP 5.1 systemd run command

### ISSUE THREAD

**Issue by igarny** [perfsonar/perfsonar-testpoint-docker#41]
Hi guys

I am not able to even run the container from pS Testpoint-systemd: v5.1.0b1-systemd 

https://github.com/perfsonar/perfsonar-testpoint-docker/tree/5.1.0#systemd-based-version-recommended

without the custom tag for the image: 
It works just fine, but on CentOS

with the tag v5.1.0b1-systemd
it executes, but then stops and is not possible to start

Client: Docker Engine - Community
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:14:17 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)

**Comment by DanielNeto** [comment]
The tag `v5.1.0b1-systemd` is indeed not working. Building locally using `docker-compose.systemd.yml` works. I think the tag was built using a non-working version of the snapshot packages.

**Comment by DanielNeto** [comment]
Actually, the docker run command in the readme was missing some parameters.
Fixed it in 4b0ac1e
