### ISSUE TITLE
rsyslog.conf corruption

### ISSUE THREAD

**Issue by jtaijr** [perfsonar/perfsonar-testpoint-docker#7]
/etc/rsyslog.conf  has the following added garbage text that causes boot-up errors:

# Use default timestamp format
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

quired,      g capability is disabled by default. This feature is usually not re--More--(29%)
# not useful and an extreme performance hit

-----------------
Error in /var/log/messages:

[root@iox log]# vi /var/log/messages
Aug 24 03:31:31 iox rsyslogd: [origin software="rsyslogd" swVersion="7.4.7" x-pid="21" x-info="http://www.rsyslog.com"] start
Aug 24 03:31:31 iox rsyslogd-2184: action 'quired,' treated as ':omusrmsg:quired,' - please change syntax, 'quired,' will not be supported in the future [try http://www.rsyslog.com/e/2184 ]
Aug 24 03:31:31 iox rsyslogd-2184: action 'g' treated as ':omusrmsg:g' - please change syntax, 'g' will not be supported in the future [try http://www.rsyslog.com/e/2184 ]
Aug 24 03:31:31 iox rsyslogd-2184: action 'capability' treated as ':omusrmsg:capability' - please change syntax, 'capability' will not be supported in the future [try http://www.rsyslog.com/e/2184 ]
Aug 24 03:31:31 iox rsyslogd-3000: user name 'capabili...' too long - ignored
Aug 24 03:31:31 iox rsyslogd-2184: action 'is' treated as ':omusrmsg:is' - please change syntax, 'is' will not be supported in the future [try http://www.rsyslog.com/e/2184 ]
Aug 24 03:31:31 iox rsyslogd-2184: action 'disabled' treated as ':omusrmsg:disabled' - please change syntax, 'disabled' will not be supported in the future [try http://www.rsyslog.com/e/2184 ]
Aug 24 03:31:31 iox rsyslogd-2184: action 'by' treated as ':omusrmsg:by' - please change syntax, 'by' will not be supported in the future [try http://www.rsyslog.com/e/2184 ]
Aug 24 03:31:31 iox rsyslogd-2184: action 'default' treated as ':omusrmsg:default' - please change syntax, 'default' will not be supported in the future [try http://www.rsyslog.com/e/2184 ]
Aug 24 03:31:31 iox rsyslogd-3000: invalid character in selector line - ';template' expected
Aug 24 03:31:31 iox rsyslogd-2207: error during parsing file /etc/rsyslog.conf, on or before line 35: errors occured in file '/etc/rsyslog.conf' around line 35 [try http://www.rsyslog.com/e/2207 ]
Aug 24 03:31:31 iox bwctld[36]: FILE=sapi.c, LINE=193, BWLServerSockCreate:Address already in use
Aug 24 03:31:31 iox bwctld[36]: FILE=bwctld.c, LINE=2654, Unable to create server socket. Exiting...
Aug 24 03:31:31 iox archiver INFO     Started
Aug 24 03:31:31 iox runner INFO     Started
Aug 24 03:31:31 iox scheduler INFO     Started
Aug 24 03:31:32 iox owampd[66]: FILE=sapi.c, LINE=182, OWPServerSockCreate: Address already in use

**Comment by tonin** [comment]
Thanks for the report!

**Comment by LukeLIN-web** [comment]
I also meet this problem when I use docker container  https://hub.docker.com/r/eymaelnicolasdasilva/owamp-ubuntu
